### ISSUE TITLE
Automatically resize / recreate depth buffer

### ISSUE THREAD

**Issue by marcdownie** [pygfx/wgpu-py#107]
The ```with swap_chain as current_texture_view:``` trick causes `swap_chain` to recreate its native swap chain if the canvas it was produced from has been resized since the last `__enter__`. This makes resizing the canvas magically work --- so well you have to go looking for the resizing code. 

All is well. But then you want to have a depth texture view associated with your canvas which needs to be resized at the same time _or panic_. Any additional sugar to be poured on this? An argument `should_resize` to `draw_frame` ? Should we have a `swap_chain.size_has_changed()` ? Something else that's already there that I'm missing?

**Comment by almarklein** [comment]
Hi, thanks for reporting this. I see what you mean! I guess I'll need to play with depth buffers myself and see how to best adjust the API. For now you may have to query the canvas size for changes, I suppose ...

**Comment by almarklein** [comment]
In visvis2, we actually do have a depth buffer already. We simply do something like:
```py
        physical_size = self._canvas.get_physical_size()  
        ...
        if self._depth_texture_size != physical_size:
            self._depth_texture_size = physical_size
            self._depth_texture = device.create_texture(
                size=(physical_size[0], physical_size[1], 1),
                usage=wgpu.TextureUsage.OUTPUT_ATTACHMENT,
                dimension="2d",
                format=wgpu.TextureFormat.depth32float,
            )
```

**Comment by almarklein** [comment]
Will consider how we can improve the API though.  Not having to keep track of the current size would already help a lot, I think.

**Comment by marcdownie** [comment]
That code's working great. This is solely a question concerning the amount of pythonic-sugar you want to pour on this here (and a report of some surprise). 

(In general, I'm finding that WGPU is sharing Vulkan's need for dependency tracking among high level "objects" as soon as anything can change: shader needs reloading? well, that means that the pipeline needs rebuilding etc. and so on.)

**Comment by almarklein** [comment]
Yeah, wgpu-py remains a rather low-level API, but I hope we can make it feel consistent and predictabole. So feel free to report surprising behavior :)

**Comment by almarklein** [comment]
In #117, I add a `size` property to the texture view object. I considered something like `swap_chain.has_size_changed`, but then you have to consider some things: Compared to when? What if some other code calls that method too?

With the current change you can do something like:
```py
        with swap_chain as texture_view:
            if texture_view.size != getattr(self, "_swap_chain_size", None):
                self._swap_chain_size = texture_view.size
                self._depth_texture = device.create_texture(
                    size=texture_view.size,
                    usage=wgpu.TextureUsage.OUTPUT_ATTACHMENT,
                    dimension="2d",
                    format=wgpu.TextureFormat.depth32float,
                )
```

**Comment by almarklein** [comment]
In #117, I add a `size` property to the texture view object. I considered something like `swap_chain.has_size_changed`, but then you have to consider some things: Compared to when? What if some other code calls that method too?

With the current change you can do something like:
```py
        with swap_chain as texture_view:
            if texture_view.size != getattr(self, "_swap_chain_size", None):
                self._swap_chain_size = texture_view.size
                self._depth_texture = device.create_texture(
                    size=texture_view.size,
                    usage=wgpu.TextureUsage.OUTPUT_ATTACHMENT,
                    dimension="2d",
                    format=wgpu.TextureFormat.depth32float,
                )
```

**Comment by almarklein** [comment]
In #117, I add a `size` property to the texture view object. I considered something like `swap_chain.has_size_changed`, but then you have to consider some things: Compared to when? What if some other code calls that method too?

With the current change you can do something like:
```py
        with swap_chain as texture_view:
            if texture_view.size != getattr(self, "_swap_chain_size", None):
                self._swap_chain_size = texture_view.size
                self._depth_texture = device.create_texture(
                    size=texture_view.size,
                    usage=wgpu.TextureUsage.OUTPUT_ATTACHMENT,
                    dimension="2d",
                    format=wgpu.TextureFormat.depth32float,
                )
```
