### ISSUE TITLE
Better error messages / how to turn on validation

### ISSUE THREAD

**Issue by marcdownie** [pygfx/wgpu-py#108]
I'm wondering how (or if) I can get better backtraces / validation / logging out of wgpu-py.

I have made a mistake in my code (clearly!) and am looking at a backtrace that looks like:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ERROR_DEVICE_LOST)`', <::std::macros::panic macros>:5:6
stack backtrace:
   0:     0x7ffc57c92e19 - wgpu_swap_chain_present
   1:     0x7ffc57ca51bb - rust_eh_personality
   2:     0x7ffc57c90e44 - wgpu_swap_chain_present
   3:     0x7ffc57c9542c - wgpu_swap_chain_present
   4:     0x7ffc57c9507c - wgpu_swap_chain_present
   5:     0x7ffc57c95b5f - wgpu_swap_chain_present
   6:     0x7ffc57c956e5 - wgpu_swap_chain_present
   7:     0x7ffc57c9565c - wgpu_swap_chain_present
   8:     0x7ffc575dc4bc - wgpu_compute_pass_destroy
   9:     0x7ffc576d2882 - wgpu_compute_pass_destroy
  10:     0x7ffc578d88cb - wgpu_queue_submit
 ... up to 43
```
No line numbers, nothing useful printed before it.

I have `RUST_BACKTRACE=full`, `RUST_LOG=trace` and `VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation` and `WGPU_LIB_PATH=` a .dll downloaded by download-wgpu-native.py -os windows --arch 64 --build debug . What am I missing?

**Comment by marcdownie** [comment]
Ah; looks like I'm at least missing #96. Anything else?

**Comment by marcdownie** [comment]
Additionally it's (now) `VK_INSTANCE_LAYERS="VK_LAYER_KHRONOS_validation"`

**Comment by almarklein** [comment]
This is indeed a problem. Usually setting the `RUST_BACKTRACE` does not help much, because the additional info is not that useful. Getting #96 should help, especially since the eventual goal of wgpu-native is to validate *everything* and never panic. Because it's supposed to run from a browser too ;)

So yeah, the situation w.r.t. error messages is far from great now, but it will definitely get better over time!

**Comment by Korijn** [comment]
Now that #96 is closed and released, are we in a better shape here?

**Comment by almarklein** [comment]
We're indeed in much better shape. But it would help if we also are able to select the debug version instead of release. That *should* turn on the Vulkan validation layers. So let's leave this open to track that.

**Comment by Korijn** [comment]
> We're indeed in much better shape. But it would help if we also are able to select the debug version instead of release. That _should_ turn on the Vulkan validation layers. So let's leave this open to track that.

Well, at least in development we can already do that. At runtime you could do it with the environment variable.

**Comment by almarklein** [comment]
> But we could make it easier, by including it in the package.

Yeah, since we do ship the debug library (we do, right?) I think it would be nice to provide a way to use these without having to know the file path. Perhaps setting the env variable to "debug".

**Comment by Korijn** [comment]
> > But we could make it easier, by including it in the package.
> 
> Yeah, since we do ship the debug library (we do, right?) I think it would be nice to provide a way to use these without having to know the file path. Perhaps setting the env variable to "debug".

We don't, but I'll make it happen :) It's not very hard
