### ISSUE TITLE
Separate WgpuCanvas into toplevel and subwidget classes

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#142]
A bit nitpicking, but ...

Right now we've implemented the GUI's to do:
```py
from wgpu.gui.whichever import WgpuCanvas
```
This makes the examples nicely consistent. Also, that class can be instantiated to work as a toplevel widget or a subwidget.  I guess we did it this way because it's trivial with Qt. For wx I had to use some `__new__` to make it work (#141). For other GUI backends it may similarly not be easy.

I propose something like:
```py
from wgpu.gui.whichever import WgpuCanvas
from wgpu.gui.whichever_support_subwidgets import WgpuCanvasWidget
```

**Comment by Korijn** [comment]
Let's try and also support ipython notebooks before we spend time refactoring existing backends... just so we have a little broader scope.
