### ISSUE TITLE
Renew Pypi token

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#148]
I revoked the current Pypi token because there was some suspicious activity. As an alternative to letting CI push to Pypi, we can also create a script to run locally, that downloads the release builds from Github and then pushes that to Pypi. Safer, but one extra step.

### Details about the activity

There were two PR's opened, that were also closes soon thereafter, and the PR's seem to be fully deleted too, just like the user who created the PR's. The email notification looked like this:
![image](https://user-images.githubusercontent.com/3015475/113625660-7c84bc80-9661-11eb-9da8-948869980b0d.png)

This looks like an attempt to steal secret data, and the only thing that we seem to expose to our actions is a Pypi token.

**Comment by Korijn** [comment]
Just to be sure I also changed my password on pypi.

**Comment by Korijn** [comment]
Can we report this user somewhere?
