### ISSUE TITLE
Use calver?

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#184]
Idea: use calver for versioning instead of the arbitrary versioning that we have now. We're always just following the upstream API's, so we keep breaking the API, so semver would not make sense anyway.

If yes, the next version will be `21.9.1` (or maybe `2021.9.1`?)

**Comment by Korijn** [comment]
Are you saying the upstream API never going to stabilize and adopt semver?

I'm not a fan of calver to be honest. I like being able to tell how much work an upgrade is going to be by looking at the version number.

**Comment by almarklein** [comment]
> Are you saying the upstream API never going to stabilize and adopt semver?

I think wgpu-native and webgpu API will have breaking changes until they reach a certain stage, after which at least webgpu should be *really* stable.

> I like being able to tell how much work an upgrade is going to be by looking at the version 

It's kindof my point that I don't think this will work for us, since there will always be breaking changes, until webgpu reaches "1.0", and then we'll rarely have any breaking changes. Therefore the current version number feels very arbitrary. With calver the version number at least means something :)

**Comment by Korijn** [comment]
How about this:

* Update wgpu-native -> major version bump
* Internal API changes/fixes -> semver rules apply

**Comment by Korijn** [comment]
Who knows, we might reach 2021 major version ;)
