### ISSUE TITLE
Cannot get adapter on somewhat older Windows laptop

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#203]
TL;DR; On older Windows machines, make sure your graphics drivers are up-to-date, enabling Vulkan 1.2+

Machine:
* A 5 year old HP Pavilion x360 Convertible
* Intel(R) Core(TM) i3-6100U CPU
* Windows 10 x64

Wgpu won't give me an adapter, instead it errors with:
```
viewport Y-flip is not supported, hiding the adapter: Intel(R) HD Graphics 520
thread '<unnamed>' panicked at 'Unable to request adapter: NotFound', src\device.rs:49:10
```

The wgpu code that raises the error is here:
https://github.com/gfx-rs/wgpu/blob/f25a45f4e2588ed39183dc068b69f2aebfa6aa66/wgpu-hal/src/vulkan/adapter.rs#L858-L867
![image](https://user-images.githubusercontent.com/3015475/141990838-f2299da6-e57b-4af2-b383-03b9cd88f44c.png)

**Comment by almarklein** [comment]
I can make it work, sortof by doing both of these:
* Make it use DX12, either by forcing it, or by disabling the windows-specific override to use Vulkan.
* Disable the `WGPUNativeFeature_TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES`.

However, without that native-feature-flag, float32 textures cannot be interpolated, and we assume that they do in pygfx.

**Comment by Korijn** [comment]
Well.. intel graphics are typically very lacking on the feature spectrum.

**Comment by almarklein** [comment]
> Well.. intel graphics are typically very lacking on the feature spectrum.

Yes, but 5 years is not *that* old ...

**Comment by almarklein** [comment]
My Vulkan version was 1.0.31, which is smaller than 1.2, so it ticks one of the checks in the Rust code above. I tried to upgrade my graphics driver, which was ... interesting. The short summary/recipy is:

* Open the Intel driver detection page: https://www.intel.com/support/go/gfx/dl.html
* Let it detect your system settings, and search for the graphics section.
* There you find a button to install the driver.
* Alternatively, it may tell that you have custom drivers from your laptop manufacturer (e.g. HP). You could try to upgrade these instead. I personally found that these were outdated (from 2018), so instead I uninstalled my current graphics driver and went back to the first bulletpoint of this list.

Eventually, it now works again! Using the Vulkan backend and with float-sampling enabled! 🎉 

Takeaway: on older machines you may want to make sure your graphics driver is up-to-date (with the vanilla Intel drivers).
