### ISSUE TITLE
Download binary when doing a dev install

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#211]
Would be nice to download the native lib when one does `pip install -e .`

On the other hand, maybe not. Because one would have to run the download script on each new version. So maybe its better to let devs getting used to run the download script whenever they update, including on their first checkout.

**Comment by Korijn** [comment]
I have been thinking about this since day one!

**Comment by Korijn** [comment]
We can do both, maybe? You can still run the script manually, even if it has run automatically.

We do need to deal with sdist installs though; the script won't be available there, I think?

**Comment by almarklein** [comment]
> We can do both, maybe? 

Right. If someone does a `git pull`, our version match logic will produce a warning if a new lib is required. Would be good to add some info to that warning. Something like "if this is a dev install, run the download script to update the binary lib".

Good point about the sdist installs. We can also download the lib for these, I suppose?

**Comment by Korijn** [comment]
We should be mindful that in the future sdist installs will break if the URL embedded in the package ever goes out of sync. I'm inclined to think we may be overlooking a simple alternative.

**Comment by almarklein** [comment]
Revisiting this issue ...

My current opinion is that the logic to download the binary is better left in a self-contained module that is only available on a dev checkout (not an sdist install). So things are good as they are. We now also have nice error messages that explicitly tell the user to run the download script when necessary, so I think we've got it all covered and can close this.
