### ISSUE TITLE
issue with depth_stencil

### ISSUE THREAD

**Issue by mikeny07** [pygfx/wgpu-py#228]
When running the cube example by adding the depth_stencil state in the render pipeline

```
depth_stencil={
        "format": wgpu.TextureFormat.depth24plus_stencil8,
        "depth_write_enabled": True,
        "depth_compare": wgpu.CompareFunction.less_equal,
},
```

Then create a depth texture:

```
size = canvas.get_physical_size()
depth_texture = device.create_texture(
      size=(size[0], size[1], 1),
      dimension=wgpu.TextureDimension.d2,
      format=wgpu.TextureFormat.depth24plus_stencil8,
      usage=wgpu.TextureUsage.RENDER_ATTACHMENT
)
```

Next, add the depth stencil attachment to the render pass:

```
render_pass = command_encoder.begin_render_pass(
        color_attachments=[
            {
                "view": current_texture_view,
                "resolve_target": None,
                "load_value": (0.0, 0.0, 0.0, 1.0),
                "store_op": wgpu.StoreOp.store,
            }
        ],
        depth_stencil_attachment={
            "view": depth_texture.create_view(),
            "depth_load_value": 0.1,
            "depth_store_op": wgpu.StoreOp.store,
            "stencil_load_value": wgpu.LoadOp.load,
            "stencil_store_op": wgpu.StoreOp.store,
        }
)
```

However, when running the example, the system throws the following error:

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\ec1d022\wgpu-core\src\track\mod.rs:472:50

Platform:
On windows 10 with wgpu-py version 0.7.1 (same error occurs on 0.6.0)

**Comment by almarklein** [comment]
The corresponding code in wgpu-core is

https://github.com/gfx-rs/wgpu/blob/97e6ea7b7170b1d90dc4ae0670b89d2f38942c29/wgpu-core/src/track/mod.rs#L455-L478

Hard to tell what it is exactly, but to me it looks like its trying to use a resource that has been removed already. Could you try storing the object returned by `depth_texture.create_view()` so it's `__del__` wont be called?

**Comment by jack1232** [comment]
Tried to store the object returned by depth_texture.create_view(), the error message in deed disappears, but nothing is rendered on the screen. However, the cube shows on the screen again by setting depth_stencil=None in the render pipeline.

**Comment by mikeny07** [comment]
It works. Thanks.
