### ISSUE TITLE
Using the wheel with Shift swaps horizontal/vertical

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#240]
* On MacOS: for glfw, qt, and jupyter, using shift sets dy to 0 and sets dx instead.
* On Windows, for glfw and qt holding shift does not affect the wheel's dx and dy.
* On Linux: todo

Not sure where to deal with this. Here or in pygx event handlers. I guess it depends on how this differs per platform.

**Comment by Korijn** [comment]
As far as I know this works the same on all platforms.

**Comment by almarklein** [comment]
I'm seeing something different :)

**Comment by almarklein** [comment]
After some thought, I don't think we can do much about it: if you see Shift, a zero dy and a nonzero dx, it might as well be a true horizontal scroll (e.g. via the trackpad). In fact, the reported behavior only occurs when using the mouse, not when using the touchpad, and we cannot distinguish between them.

My inclination is to handle this downstream using something like `d = dx or dy` where you don't necessarily need to differentiate between vertical/horizontal.

**Comment by almarklein** [comment]
> My inclination is to handle this downstream using something like `d = dx or dy`

I've done this now in the gizmo pr.

I also added notes in the jupyter_rfb event spec: https://github.com/vispy/jupyter_rfb/pull/55

With that, I think we can close this issue.
