### ISSUE TITLE
examples need update, not working

### ISSUE THREAD

**Issue by pieper** [pygfx/wgpu-py#261]
I am able to pip install wgpu, but the examples are not working because they use the `@` syntax rather than the `[[ ]]` syntax.  After changing to the `[[ ]]` in the `compute-noop.py` example it runs, but then gives these errors and then aborts.

```
Unexpected resource type: Array { base: [1], size: Dynamic, stride: 4 }
Unexpected resource type: Array { base: [1], size: Dynamic, stride: 4 }
```
this is with:
```
>>> import wgpu
>>> wgpu.__version__
'0.7.7'
```

**Comment by Korijn** [comment]
Try grabbing the examples from git tag v0.7.7.

Note that in general we can't guarantee examples from the tip of the master branch will work with the last release. For example, right now we are transitioning to a newer version of wgpu, so the shader syntax is being changed.

If you really want to work with the master branch, then you should not install from pip, and instead check out the "Developers" section from the README.

**Comment by pieper** [comment]
Ah, great, makes sense that does work.

Thanks for the quick response!
