### ISSUE TITLE
"pointer_move" event seems not working

### ISSUE THREAD

**Issue by mikeny07** [pygfx/wgpu-py#269]
The "pointer_move" and "wheel" events work in the previous versions (<= 0.7.6), but they seem not working anymore in the new version 0.8.0. For example,  in the events.py example, changing the code
```py
class MyCanvas(WgpuCanvas):
    def handle_event(self, event):
        if event["event_type"] == "pointer_move":
            print(event)
```
gives no result. 

But it seems working when using
```py
canvas.add_event_handler(mouse_event, "pointer_move", "wheel")
```
There are some issues by setting events via subclass.

**Comment by almarklein** [comment]
Fixed. New release should be on pypi in a minute.

**Comment by mikeny07** [comment]
Great. Thank you for the excellent work.
