### ISSUE TITLE
Rust panic after creating hundreds of renderers/canvases

### ISSUE THREAD

**Issue by Korijn** [pygfx/wgpu-py#275]
I still need to figure out how to reliably reproduce this, but in a script I was batch running yesterday, my computer would actually lock up* after a rust panic. The problem went away after I modified the script to reuse the same canvas and renderer instance, instead of creating new ones for every image I was drawing.

\* Lock up as in, no response to ctrl+c, windows task manager would not respond, ctrl+alt+del does nothing, shutting down/rebooting gets stuck in a black screen... only way out was to hold the power button for 30 seconds.

**Comment by almarklein** [comment]
> only way out was to hold the power button for 30 seconds.

Umphf ... that's a proper lock up.

Would be interesting to see whether it's the `n`  renderers or the canvases that causes it. First thought is a missing destructor or something.
