### ISSUE TITLE
[GLFW] Gui layer run() method does not return after closing window

### ISSUE THREAD

**Issue by Korijn** [pygfx/wgpu-py#277]
Like the title says, closing a `WgpuCanvas` window does not cause the event loop to return, and thus `run()` to return. Should be pretty easy?

**Comment by almarklein** [comment]
As far as I can tell this is the (intended) behavior. What GUI backend does not do it this way?

**Comment by Korijn** [comment]
GLFW for example uses `loop.run_forever()` instead of `loop.run_until_complete(...)`:

https://github.com/pygfx/wgpu-py/blob/e1987d044eaab480f03b08c2ed97e7f2faae8446/wgpu/gui/glfw.py#L514-L518

**Comment by almarklein** [comment]
Looks like this has been fixed a while ago in #319.
