### ISSUE TITLE
disable sampling filter for textures

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/wgpu-py#280]
Hi, not sure what's the best place to put this so feel free to transfer/redirect me. 

I was trying to figure out if it's possible to disable the `filter` set in `pygfx` [`TextureView`](https://github.com/pygfx/pygfx/blob/main/pygfx/resources/_texture.py#L274) and found that it eventually ends up calling [`wgpu::FilterMode`](https://wgpu.rs/doc/wgpu/enum.FilterMode.html) which seems to be directly from the [WGPU API](https://gpuweb.github.io/gpuweb/#enumdef-gpufiltermode). It only has options for `nearest` and `linear`. I was wondering if there's any way to bypass the sampling filter or turn it off? This would make it easy to display scientific heatmaps and rasterplots without interpolation.

Thanks!

**Comment by almarklein** [comment]
I think that `nearest` is what you mean with off :)

Longer answer: strictly speaking a pixel is an (infinitely small) point. To fill in the space between the pixels you need *some* interpolation method. With `nearest` you pick the value of the nearest pixel. With linear you linearly combine the values of the 2 (1D), 4 (2D) or 8 (3D) nearest pixels. And then there are a variety of cubic interpolation methods that take more pixels into account.

**Comment by kushalkolar** [comment]
@rob-the-bot thanks for looking into it further!

I think I found where it's actually creating the `TextureView` for the image data that is set to the `Geometry` `grid`, https://github.com/pygfx/pygfx/blob/d6941399fc887f2a26879f64169000a53afdfaa1/pygfx/renderers/wgpu/imagerender.py#L70

Setting this to nearest works for me, note that this is running as a desktop window so you don't see the jpeg smoothing the edges as seen in notebooks via `jupyter_rfb`

![image](https://user-images.githubusercontent.com/9403332/172733358-227faf7d-ae71-4d15-bed9-ca5c2e3f9132.png)

**Comment by kushalkolar** [comment]
I'm wondering what's the best way to customize the filter (and other `Texture`) settings for the displaying Images:

1. Always use a `TextureView`, so then:
```python
pygfx.Image(
    pygfx.Geometry(grid=TextureView(<data>, filter=<filter>)
    ...
```

Is there any downside to using `TextureView` rather than `Texture` for setting `grid`?

2. The other possibility is adding `filter` as a kwarg to `Texture`, which it can pass to `TextureView` instances when it creates them. I'm thinking that the first idea is better since it doesn't modify the API.

**Comment by almarklein** [comment]
> Is there any downside to using TextureView rather than Texture for setting grid?

Pygfx sometimes allows specifying a texture when it really needs a textureview, and then creates the view itself. I think it would be a good idea to make this more consistent and simply require a view where it needs one.

**Comment by almarklein** [comment]
@rob-the-bot I think you want to set the textureview for the grid to nearest, and can probably leave the colormap to linear.

**Comment by kushalkolar** [comment]
> Pygfx sometimes allows specifying a texture when it really needs a textureview, and then creates the view itself. I think it would be a good idea to make this more consistent and simply require a view where it needs one.

Thanks! It would be very useful (for performance) to set the`kwargs` that are used by [`Texture.get_view()`](https://github.com/pygfx/pygfx/blob/d6941399fc887f2a26879f64169000a53afdfaa1/pygfx/resources/_texture.py#L65) when creating a `Texture` instance. Because the [`image_renderer`](https://github.com/pygfx/pygfx/blob/d6941399fc887f2a26879f64169000a53afdfaa1/pygfx/renderers/wgpu/imagerender.py#L70) just calls it with `filter="linear"`.

If you think this addition is appropriate I can implement it :) 

To elaborate:

This is slow
```python
texture_view = pygfx.Texture(<data>, dim=2).get_view(filter="nearest")

image = pygfx.Image = pygfx.Image(
    pygfx.Geometry(grid=texture_view),
    pygfx.ImageBasicMaterial(clim=<minmax>, map=<some cmap>)
)

def animate(new_data):
    image.geometry.grid = pygfx.Texture(data, dim=2).get_view(filter="nearest")
```

This is fast but uses the default `filter="linear"`:
```python
texture = pygfx.Texture(<data>, dim=2)

image = pygfx.Image = pygfx.Image(
    pygfx.Geometry(grid=texture),
    pygfx.ImageBasicMaterial(clim=<minmax>, map=<some cmap>)
)

def animate(new_data):
    image.geometry.grid.data[:] = data
    image.geometry.grid.update_range((0, 0, 0), image.geometry.grid.size)

```

**Comment by almarklein** [comment]
I think the correct approach would be:
```py
texture = pygfx.Texture(<data>, dim=2)

image = pygfx.Image = pygfx.Image(
    pygfx.Geometry(grid=texture.get_view(filter="nearest")),
    pygfx.ImageBasicMaterial(clim=<minmax>, map=<some cmap>)
)

def animate(new_data):
    image.geometry.grid.data[:] = data
    image.geometry.grid.update_range((0, 0, 0), image.geometry.grid.size)
```

That said, the textureview is an abstraction that is extra cognitive load if you're just interested in an image. So we could think about making it a bit simpler. Some options, just to list some ideas:

* Let the texture define the default kwargs for the view (what you suggested).
* Let a texture have an internal view that is used when the texture is passed, and in the texture's init you can specify the filtering for it.
* Define a `SimpleTexture` that combines a texture and view in one.

As a side-note: in pygfx we don't support using part of a buffer yet (using offset and size). It might be that a future API for that includes something like a buffer view. If that happens, it would be good if we could keep the texture/textureview and buffer/bufferview API's similar.

**Comment by Korijn** [comment]
My vote is on the second option!

I don't think the texture/view abstraction is all that complicated. We could perhaps document it more clearly.

My simplified understanding is that the texture is just a reference to the data, and the view is the sampling configuration that you want to use with a texture. It's a pretty powerful concept in the sense that you can sample the same data with different views!

**Comment by almarklein** [comment]
Another option that I mentioned in an earlier comment:
* Disallow passing a texture where a textureview is required. We'd have to adjust some of our examples, and we could document the distinction better.

**Comment by kushalkolar** [comment]
> I think the correct approach would be:
> 
> ```python
> texture = pygfx.Texture(<data>, dim=2)
> 
> image = pygfx.Image(
>     pygfx.Geometry(grid=texture.get_view(filter="nearest")),
>     pygfx.ImageBasicMaterial(clim=<minmax>, map=<some cmap>)
> )
> 
> def animate(new_data):
>     image.geometry.grid.data[:] = data
>     image.geometry.grid.update_range((0, 0, 0), image.geometry.grid.size)
> ```
>

This does not work, 

```
    image.geometry.grid.data[:] = np.random.rand(512, 512).astype(np.float32) * 255
AttributeError: 'TextureView' object has no attribute 'data'
Draw error: 'TextureView' object has no attribute 'data' (2)
```

> * Let a texture have an internal view that is used when the texture is passed, and in the texture's init you can specify the filtering for it.

Do you mean a `TextureView` instance is always present in a `Texture` instead of a new instance created each time `get_view()` is called?

**Comment by almarklein** [comment]
Closing. Following up in https://github.com/pygfx/pygfx/issues/350

**Comment by kushalkolar** [comment]
> Try:
> 
> ```python
> image.geometry.grid.texture.data[:] = np.random.rand(512, 512).astype(np.float32) * 255
>                      /\
> ```
> 
> > Do you mean a TextureView instance is always present in a Texture instead of a new instance created each time get_view() is called?
> 
> That would be the idea of that option, yeah.

just want to followup because I finally got around to trying this and it works:

```python
world_object.geometry.grid.texture.data[:] = np.random.rand(512, 512)
world_object.geometry.grid.texture.update_range((0, 0, 0), size=world_object.geometry.grid.texture.size)
```
