### ISSUE TITLE
Errors with PyQt6 (6.3.1) backend

### ISSUE THREAD

**Issue by rkspsm** [pygfx/wgpu-py#282]
I was trying to run basic examples with PyQt6 backend, and this is the code which I ran and it threw errors :

```
from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6.QtWidgets import *
[changes.txt](https://github.com/pygfx/wgpu-py/files/8952153/changes.txt)

import wgpu.backends.rs
from wgpu.gui.qt import WgpuCanvas
```

The error was in the file wgpu/gui/qt.py. On furthur inspection there were actually several errors, all of them resulting from names of things changed. Eg. All Key_* values are in Qt.Key instead of directly in Qt. After fixing the errors, I was able to run the above code, as well as the triangle_qt example.

I attach the diff patch of the changes I made to the above mentioned file.
[changes.txt](https://github.com/pygfx/wgpu-py/files/8952158/changes.txt)

**Comment by almarklein** [comment]
I think we don't really support pyqt6 yet. A PR would be welcome. One option could be to make use of [qtpy](https://github.com/spyder-ide/qtpy), though I'm not sure whether it supports PyQt6 already (it didn't some time ago, because PyQt6 differs quite a bit from the rest).

**Comment by rkspsm** [comment]
Well, I didnt submit a PR because I merely ran the triangle example. I have some experience with PyQt (both 5 and 6), but not with webgpu or 3d graphics programming in general besides triangle examples, and that too from vulkan only, as I find opengl too obtuse. I was exploring webgpu to expand my understanding of relatively low level gpu programming.
