### ISSUE TITLE
cannot import backend after installing python package libwgpu-release.so missing

### ISSUE THREAD

**Issue by alexMilmore** [pygfx/wgpu-py#286]
have ran
```
pip install wgpu
```
and
```
python3 -m pip install wgpu
```
on 2 seperate machines, both fail to run ```import wgpu.backends.rs```
with the following error msg

```  
File "<stdin>", line 1, in <module>
  File "/home/alex/.local/lib/python3.8/site-packages/wgpu/backends/rs.py", line 44, in <module>
    from .rs_ffi import ffi, lib, check_expected_version
  File "/home/alex/.local/lib/python3.8/site-packages/wgpu/backends/rs_ffi.py", line 85, in <module>
    lib = ffi.dlopen(get_wgpu_lib_path())
  File "/home/alex/.local/lib/python3.8/site-packages/wgpu/backends/rs_ffi.py", line 74, in get_wgpu_lib_path
    raise RuntimeError(f"Could not find WGPU library in {embedded_path}")
RuntimeError: Could not find WGPU library in /home/alex/.local/lib/python3.8/site-packages/wgpu/resources/libwgpu-release.so
```
looking in the directory ```libwgpu-release.so``` is not there.
Any ideas what I've done wrong?

Python version: 3.8.10
OS: Ubuntu 20.04

**Comment by alexMilmore** [comment]
The contents of my ```lib/python3.8/site-packages/wgpu/resources/``` dir is

* ```__init__.py```
* ```__pycache__```
* ```webgpu.h```
* ```webgpu.idl```
* ```wgpu.h```

**Comment by almarklein** [comment]
There are binary wheels for manylinux for both 32 and 64 bit on Pypi. I double-checked and they contain the prebuild library. Could you show a log for `pip install -U wgpu` please?

**Comment by alexMilmore** [comment]
output of ```pip install -U wgpu```
```
Requirement already up-to-date: wgpu in ./.local/lib/python3.8/site-packages (0.8.1)
Requirement already satisfied, skipping upgrade: cffi>=1.15.0rc2 in ./.local/lib/python3.8/site-packages (from wgpu) (1.15.1)
Requirement already satisfied, skipping upgrade: pycparser in ./.local/lib/python3.8/site-packages (from cffi>=1.15.0rc2->wgpu) (2.21)
```

**Comment by Korijn** [comment]
Can you add `--force-reinstall`?

**Comment by almarklein** [comment]
Probably, for whatever reason, pip first installed from the tarbal (or Github) instead if using the wheel. Glad it's fixed :)
