### ISSUE TITLE
Update to latest wgpu spec

### ISSUE THREAD

**Issue by Korijn** [pygfx/wgpu-py#289]
This issue is to track the steps required for updating wgpu-native.

### Preparations

* [x] Merge open wgpu-py PR's:
  * [x] https://github.com/pygfx/wgpu-py/pull/316
  * [x] https://github.com/pygfx/wgpu-py/pull/315
* [x] Release wgpu-py (pre-update version)
* [x] Merge running Pygfx issues/PR's.
  * [x] https://github.com/pygfx/pygfx/pull/404
  * [x] https://github.com/pygfx/pygfx/pull/405
* [x] Release PyGfx.

### Update minimal

* [x] Updates, fixes, and improvements in wgpu-native 
  * [x] https://github.com/gfx-rs/wgpu-native/pull/234
  * [x] https://github.com/gfx-rs/wgpu-native/pull/235
  * [x] https://github.com/gfx-rs/wgpu-native/pull/233
  * [x] https://github.com/gfx-rs/wgpu-native/pull/236
* [x] Release wgpu-native.
* [x] Update wgpu-py
  * [x] #327
  * [x] #329
* [x] Release wgpu-py
* [x] Update PyGfx: [#443](https://github.com/pygfx/pygfx/pull/443)
* [ ] Release PyGfx.

### Update continued

* [x] More wgpu-py work
  * [x] Look into https://github.com/gfx-rs/wgpu-native/pull/148 -> still no luck
  * [x] https://github.com/pygfx/wgpu-py/pull/332
  * [x] https://github.com/pygfx/wgpu-py/pull/331
  * [x] https://github.com/pygfx/pygfx/pull/445
  * [x] #264
  * [ ] #306 
  * [x] #333
  * [x] #334
  * [x] #335
* [x] Release wgpu-py
* [x] Update PyGfx
  * [x] https://github.com/pygfx/pygfx/pull/443
  * [x] https://github.com/pygfx/pygfx/pull/446
  * [x] https://github.com/pygfx/pygfx/pull/445
* [x] Release PyGfx.

**Comment by almarklein** [comment]
Done 😅
