### ISSUE TITLE
Remove debug builds from pypi

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/wgpu-py#291]
This is a suggestion rather than an issue. 

I'm currently setting up wgpu-py and pygfx on my Windows workstation and I've noticed that wgpu-py ships with both the debug and the release library (.dll) of libwgpu when installed from pypi. I wonder if it would make sense to only include the release build on pypi, since most users that `pip install wgpu` would expect to get the release version of wgpu. This would bring down the package size in pypi and might have positive performance implications, too. It would also ease CI, as we would only compile the release build instead of compiling both.

**Comment by Korijn** [comment]
I seem to recall that it's helpful in development and debugging; you won't get any stacktraces from wgpu-native with the release build for example. I'm sensitive to the argument of bringing down package size.

> I wonder if it would make sense to only include the release build on pypi, since most users that pip install wgpu would expect to get the release version of wgpu.

Technically, you get both. The release build is used by default. The debug build is only used if you set the environment variable `WGPU_DEBUG=1` when importing wgpu.

> This would bring down the package size in pypi

Yes! Unzipped I think it accounts for about a little over 50% of filesize, but zipped the ratio is less significant. I would assume the two binaries have a lot of commonalities so they compress well. Anyway; less data transferred, means less impact on environment, so I'm sensitive to this one!

> and might have positive performance implications, too

Not at runtime, but it would benefit download and install time for users, and build time for us.

> It would also ease CI, as we would only compile the release build instead of compiling both.

Well, we actually don't compile anything. We maintain the build process on the upstream [wgpu-native](https://github.com/gfx-rs/wgpu-native) repo, and download binaries from their github releases in our workflows. See `download-wgpu-native.py`.

So our CI would not be affected if we drop the debug builds.

**Comment by almarklein** [comment]
Like a year or two ago, the debug builds were useful for when wgpu-native was used in the wrong way to get some more info on what went wrong. Over time, the error reporting of wgpu-native has improved a lot, via API mechanisms. So right now I'd say the debug builds are for devs that want to debug wgpu-py/wgpu-native particularly.  Actually, I think I have not used the debug build for over a year :)

So I agree with @Korijn's proposal - let's remove them from the wheels.

**Comment by FirefoxMetzger** [comment]
I see. If we are using the release build by default then there is indeed only package size.

I was briefly thinking if it would be interesting to only ship the release build and give a `wgpu.download_debug()` option for people that need the debug build. However, that has quite a few security implications and shipping the debug build via pypi is much easier.

> Well, we actually don't compile anything. We maintain the build process on the upstream [wgpu-native](https://github.com/gfx-rs/wgpu-native) repo, and download binaries from their github releases in our workflows. See download-wgpu-native.py.

Right, that explains the behavior I encountered in https://github.com/pygfx/wgpu-py/issues/292. 

> So I agree with @Korijn's proposal - let's remove them from the wheels.

Sounds good to me, too 👍

**Comment by Korijn** [comment]
OK, so then you would need to modify this section of `setup.py` to exclude the debug binaries:

https://github.com/pygfx/wgpu-py/blob/f5214264769ae022ed1fb4ad8dc8527c3719962f/setup.py#L21-L27
