### ISSUE TITLE
Several test dependencies missing from dev-requirements.txt

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/wgpu-py#293]
I'm following the [dev setup](https://github.com/pygfx/wgpu-py#developers) instructions and there seem to be two test-time dependencies missing. In particular, I had to manually install

- pyinstaller
- psutil

before I could get the tests to collect (via `pytest .`). Would you like me to add them in `dev-requirements.txt`?

**Comment by Korijn** [comment]
Works for me!
