### ISSUE TITLE
Document available backends

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/wgpu-py#300]
During my meeting with @almarklein this morning we discussed that it would be good to create some documentation on available backends for wgpu and pygfx. 

Towards this, I did a brief search of the repo and the docs, but I couldn't find a list of backends. I am currently aware of three backends:

- Qt (pyside6) 
- glfw 
- jupyter_rfb (currently broken?)

Are there any other backends that could be used with wgpu?

**Comment by FirefoxMetzger** [comment]
On the same token, we may wish to mention in the readme that one has to manually install a suitable backend and add a reference to this information from pygfx.

**Comment by almarklein** [comment]
See https://github.com/pygfx/wgpu-py/tree/main/wgpu/gui:
* glfw: our default that is lightweight and stable.
* Qt: any of "PySide6", "PyQt6", "PySide2", "PyQt5")
* wx
* jupyter_rfb: (not exactly broken, but needs to be updated to work with the latest jupyter-widgets)
* offscreen: mostly intended for tests etc.

**Comment by toloudis** [comment]
I'd just like to leave a note here that the offscreen backend can be useful for headless rendering, e.g. automating rendering on a remote machine that has a gpu and a vulkan driver - I have been looking at this for a python port of my volume renderer called agave.
