### ISSUE TITLE
Branch protection

### ISSUE THREAD

**Issue by Korijn** [pygfx/wgpu-py#301]
Let's use this issue to discuss the branch protection settings. This is my current (applied) proposal, any feedback is welcome!

If you all support this configuration, I will apply it to the other repositories as well.

I've set up `CODEOWNERS` like this:

https://github.com/pygfx/wgpu-py/blob/d34337e093a4c5f6fd1a14adcbb61a80d603bc37/.github/CODEOWNERS#L1

I've set up branch protection for `main` like this:

![image](https://user-images.githubusercontent.com/1882046/199700915-69745390-66fd-4b34-9098-2d41eb94cac4.png)

**Comment by Korijn** [comment]
I misunderstood lock branch, so I unchecked that one.

To be clear, you are all allowed to hit the merge button once you've got my approval in.

**Comment by FirefoxMetzger** [comment]
> If you all support this configuration, I will apply it to the other repositories as well.

Hm, my suggestion is to apply this here first for a week or two, see if/how it works, and then scale it to the other repos once we know that this is the way we want to move forward :)

Some thoughts:

- I'm not 100% sure how the first box interacts with the need for code-owner approval. My guess is that they are independent, so we might not need or want this first box. The thing that I think is important here is that requested changes will block a merge. This means that the person that requested the changes needs to approve the PR before the merge can move forward (on top of any code owners). 
- Personally, I would not check the `Dismiss stale PR approvals` box. It would mean more work for you because small things like "LGTM, just fix this spelling mistake" would require another new review/approval from you after the typo was fixed. If this is contractually required that's what it is, but otherwise, you might choose to omit it.
- The "Require conversation resolution before merging" may also be more restrictive than we may want. If the conversation isn't about the code, but about something that results in new issues being created as a result it still needs to be resolved manually. This is fine for small PRs, but once they get long (for bigger PRs) GH will hide comments and you end up digging through the PRs history to find the one thing you forgot to resolve.

**Comment by FirefoxMetzger** [comment]
I will go find something small in the readme that can be improved and then create a PR for it so that we can test the rules :)

**Comment by almarklein** [comment]
> If the conversation isn't about the code, but about something that results in new issues being created as a result it still needs to be resolved manually. 

In my experience with big PR's I think this might actually be helpful, to ensure that all points are e.g. converted to an issue.

**Comment by Korijn** [comment]
> Hm, my suggestion is to apply this here first for a week or two, see if/how it works, and then scale it to the other repos once we know that this is the way we want to move forward :)

Sure!

> Some thoughts:

> * I'm not 100% sure how the first box interacts with the need for code-owner approval. My guess is that they are independent, so we might not need or want this first box. The thing that I think is important here is that requested changes will block a merge. This means that the person that requested the changes needs to approve the PR before the merge can move forward (on top of any code owners).

They are indeed independent. You need 1 approval, and you need 1 approval from me as the code owner, so you can satisfy both conditions by getting just my approval. If you don't have that, you can't merge.

> * Personally, I would not check the `Dismiss stale PR approvals` box. It would mean more work for you because small things like "LGTM, just fix this spelling mistake" would require another new review/approval from you after the typo was fixed. If this is contractually required that's what it is, but otherwise, you might choose to omit it.

Well, in that scenario, I agree, but there is also the scenario where I say "LGTM, just change this one small thing" and it turns out to be trigger a somewhat larger scale change like a refactor. In those cases I want to see the changes before they get merged. Don't worry, I can handle some additional approval/review, context switching is what I do best. You will rarely need to wait on me, pinky promise!

> * The "Require conversation resolution before merging" may also be more restrictive than we may want. If the conversation isn't about the code, but about something that results in new issues being created as a result it still needs to be resolved manually. This is fine for small PRs, but once they get long (for bigger PRs) GH will hide comments and you end up digging through the PRs history to find the one thing you forgot to resolve.

Well, that's a benefit in my mind! If you have to dig to find it, you probably did forget about it, and may still need to do something, potentially important.

**Comment by FirefoxMetzger** [comment]
> You need 1 approval, and you need 1 approval from me as the code owner, so you can satisfy both conditions by getting just my approval.

Hm, so the main effect of adding this option is that everybody that reviewed must be happy (no changes requested) for a merge to be possible? (you have to approve in all cases, which fulfills the required number of reviews) Sure, we can try that.

> I agree, but there is also the scenario where I say "LGTM, just change this one small thing" and it turns out to trigger a somewhat larger scale change like a refactor.

Fair point. I was thinking that those cases are covered by you leaving a review with "request changes", which would block merging in any case.

> Also, you can avoid all of that hassle and just use the conversations tool, which groups by unresolved/resolved:

Interesting. I didn't know GH had this feature. Learned something new today. Thanks @Korijn :)

**Comment by Korijn** [comment]
I've copied over the settings to the pygfx repo.

**Comment by almarklein** [comment]
> But I have to select each of them individually.

Yeah, that seems odd. But in the PR the checks have "required" in them, so I guess it's easy to spot when one is not required at some point?

**Comment by FirefoxMetzger** [comment]
This is indeed odd. We could partly work around this by having a check that depends on all the necessary ones and make it the only required check. This way, the config for what is required lives in the same file as the checks themselves which should make it less likely to forget.

Alternatively, we could restrict merges to admins and ask them to make the final judgment on which tests should or shouldn't pass.

**Comment by Korijn** [comment]
I'm happy with the current settings. How about you @almarklein and @FirefoxMetzger ?

**Comment by almarklein** [comment]
Yep!

**Comment by FirefoxMetzger** [comment]
no complaints here.
