### ISSUE TITLE
Add a simple way to get a canvas' event loop

### ISSUE THREAD

**Issue by FirefoxMetzger** [pygfx/wgpu-py#307]
In https://github.com/pygfx/pygfx/pull/380 we started using `sys.modules[canvas.__module__].run()` to get a canvas's run function dynamically. It would be nice if this would become an explicit feature that would allow us to do `canvas.run()`.

We would probably have to think about the implications of this on customizing the event loop, so the purpose of this issue is to discuss how such a thing would best look like.

**Comment by almarklein** [comment]
The use-case is to be able to get the run method when you only have a canvas. First thing that comes to mind is to put something on the canvas to get the run function, but that feels weird and ugly to me.

This is rather special functionality that is not needed by typical users. So my question would be whether we need to provide something at all? I assume your main concern is that the code (using `sys.modules`) feels a bit hacky?

Maybe something like this:
```
run = wgpu.gui.get_run_function_from_canvas(canvas)
```

**Comment by almarklein** [comment]
In PyGfx we look the function up via `sys.modules`, which is what a function like proposed would probably do. This seems fine for now.
