### ISSUE TITLE
Use weakrefs in `add_event_handler`?

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#318]
By registering callbacks via `add_event_handler`, references to objects are stored and can prevent objects from being cleaned up. Is this behavior that we want, or should we use weakrefs?

**Comment by almarklein** [comment]
Some options:
1. Store the given callback with a weakref. This would break e.g. lambdas and closures, so nah.
2. Store the callback, but (only) use a weakref if its a method. This could kinda work, but it can also feel inconsistent, especially since a closure can *also* hold a reference to an object.
3. Just store all callbacks by reference. If this is a problem, the caller can use weakrefs in a way that works for the use-case at hand.

I'm leaning hard towards option 3. Created #398 to "implement" that.

**Comment by Korijn** [comment]
I support that preference for #3. It doesn't need to be solved here necessarily.
