### ISSUE TITLE
[Qt, Windows] Crash when switching from monitor to monitor with different DPI values

### ISSUE THREAD

**Issue by Korijn** [pygfx/wgpu-py#352]
When I drag the window from one monitor to another, with different DPI settings, pygfx crashes:

```
❯ python .\examples\feature_demo\colormap_channels.py
QWindowsWindow::setDarkBorderToWindow: Unable to set dark window border.
Requested size 640x480 is outside of the supported range: Extent3d { width: 1600, height: 1200, depth_or_array_layers: 1 }..=Extent3d { width: 1600, height: 1200, depth_or_array_layers: 1 }
Uncaught WGPU error (Unknown):
Outdated
thread '<unnamed>' panicked at 'Unable to end render pass: RenderPassError { scope: Pass((0, 122, Vulkan)), inner: MissingAttachments }', src\command.rs:298:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Korijn** [comment]
This also happens on the examples here, so I transferred the issue.

**Comment by Korijn** [comment]
Seems like we might be resizing our rendering pipelines and buffers 1 frame too late after becoming aware of the resize event?

**Comment by almarklein** [comment]
I cannot reproduce it on MacOS with PySide 6.4.1.

**Comment by almarklein** [comment]
I can reproduce this bug on Windows. Exactly what you said: works fine on GLFW, but with Qt (PySide 6.6.0 in this case) it gives an error. The error is now a genuine Exception though, with a traceback, so I have more to go on.

**Comment by Korijn** [comment]
Given what you observed in https://github.com/gfx-rs/wgpu-native/pull/315 do you think it could be this line that needs a `None` check?

https://github.com/pygfx/wgpu-py/blob/dbb991d23f31bbbb568bbe3e6d8cb797e0f111a2/wgpu/backends/rs.py#L495

**Comment by almarklein** [comment]
Yeah. I think the equivalence would be something like `== ffi.NULL`.

**Comment by almarklein** [comment]
The crashing was fixed, but we still got warnings that we could not prevent. Looks like these will be gone soon too: https://github.com/gfx-rs/wgpu/pull/4796
