### ISSUE TITLE
Qt dark mode warning

### ISSUE THREAD

**Issue by Korijn** [pygfx/wgpu-py#354]
I get the following warning when running examples with the Qt GUI backend:

`QWindowsWindow::setDarkBorderToWindow: Unable to set dark window border.`

**Comment by Korijn** [comment]
I'm not sure how helpful this is but I can see some snapshot of the source code that emits this warning here:

https://github.com/xingbangzhou/xhcc/blob/5a7196f0b023290696f7fee159ecf5581a151485/depends/qt6.2.3/src/qtbase/src/plugins/platforms/windows/qwindowswindow.cpp#L3045

**Comment by almarklein** [comment]
I think it's because of the `winId()` method call. If I make `get_window_id()` return 1 instead of calling `winId()` then the error does not occur. There will be either a black screen or a crash because that id is obviously not valid, but no " Unable to set dark window border".

**Comment by Korijn** [comment]
Can no longer reproduce with PySide 6.6 🎉
