### ISSUE TITLE
qt.qpa.window: SetProcessDpiAwarenessContext failed

### ISSUE THREAD

**Issue by sharon92** [pygfx/wgpu-py#363]
```
qt.qpa.window: SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2) failed: COM error 0x5: Zugriff verweigert
Qt's default DPI awareness context is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2. If you know what you are doing you can overwrite this default using qt.conf (https://doc.qt.io/qt-6/highdpi.html#configuring-windows)
qt.qpa.window: SetProcessDpiAwareness(2) failed: COM error 0x80070005: Zugriff verweigert, using 1
Qt's fallback DPI awareness is PROCESS_DPI_AWARENESS. If you know what you are doing consider an override in qt.conf
```

This warning pops up because the `set_dpi_aware` variable is always set to True.
I tried importing `__version_info__ `from `QtCore `but this attribute doesnt exist in PyQt6 or 5
I am using PyQt 6.5.1

https://github.com/pygfx/wgpu-py/blob/0e2f34b91060137bac40580bc84d7ab8af7a19e7/wgpu/gui/qt.py#L102

**Comment by almarklein** [comment]
Would indeed be nice if we can suppress/avoid this warning. I don't think it does any harm, but it may give the suggestion that something is wrong, or when an actual error occurs, people may see this as the cause ...

**Comment by Korijn** [comment]
Annoyingly enough, it's something that is being printed directly to stdout in the Qt c++ source code, without any mechanism to suppress it. I don't think we can do anything about it.

**Comment by almarklein** [comment]
We do attempt to address it by checking the qt version:
https://github.com/pygfx/wgpu-py/blob/0e2f34b91060137bac40580bc84d7ab8af7a19e7/wgpu/gui/qt.py#L101-L104

The problem (now I see what @sharon92 meant with her comment) is that on PyQt we need to `QtCore.QT_VERSION_STR`. There does not seem to be a uniform way to get the QT version 😕. QtPy also queries the version differently for PyQt5 and PySide (using `QtCore.QT_VERSION_STR` and `QtCore.__version__` respectively.

**Comment by sharon92** [comment]
@almarklein yep, that's what I meant.

P.S: I am a "he" :)  Sharon is a common unisex name for south Indians, but perhaps I need to update my picture :)

**Comment by almarklein** [comment]
Oh, I'm so sorry! Sharon is a common name here (in The Netherlands) but only for woman, so I just assumed 😬

**Comment by sharon92** [comment]
@almarklein no worries. I live in Germany, and I have to say this every once in a while :)
