### ISSUE TITLE
Binary support for manylinux2010?

### ISSUE THREAD

**Issue by apontzen** [pygfx/wgpu-py#366]
First, thanks for providing this library. It’s outstanding, and I’m using it alongside some students to develop scientific visualization software for cosmological simulations.

We are using it in combination with jupyter-rfb on a cluster with beefy GPUs. However, like many HPC services, the nodes run quite old versions of linux (CentOS) which are tried-and-tested with the custom hardware. This is not something that we can change due to the wide variety of users and needs.

The underlying wgpu libraries are [built against `manylinux2010`](https://github.com/gfx-rs/wgpu-native/wiki/Binary-Releases#linux-builds) (which is fine), so I was wondering whether there is a particular rationale for `wgpu` wheels targeting the newer `manylinux_2_24`?

Thanks again

**Comment by Korijn** [comment]
First of all, the article you linked is outdated, manylinux2010 sadly does not have a recent enough version of c compilers: https://github.com/gfx-rs/wgpu-native/issues/118

So the upstream binaries are actually being built against manylinux 2 24 and 2 28 even.

**Comment by apontzen** [comment]
Ah ok! Thanks for the info.

**Comment by Korijn** [comment]
The article has been updated!
