### ISSUE TITLE
Suggestion: compute.toys integration

### ISSUE THREAD

**Issue by mikeny07** [pygfx/wgpu-py#367]
The integration of Shadertoy into wgpu-py is amazing. Now, there is a WGSL version of Shadertoy, which is called [compute.toys](https://compute.toys). This toy, based on wgpu-rs, uses WGSL compute shaders. The WGSL code used in compute.toys fits into the wgpu-py project even better than the ShaderToy with GLSL. compute.toys in wgpu-py is more like the standard, first-class wgpu-py apps because they use the same shader language.

Since you already have the Shadertoy integration in place, adding [compute.toys](https://compute.toys) to wgpu-py should be an easier task.

Here are a few examples from compute.toys:

- [https://compute.toys/view/503](https://compute.toys/view/503)
- [https://compute.toys/view/260](https://compute.toys/view/260)
- [https://compute.toys/view/107](https://compute.toys/view/107)

By the way, it seems that the Shadertoy integration does not work if the  code has image textures, for example: [https://www.shadertoy.com/view/stSBWz](https://www.shadertoy.com/view/stSBWz)

**Comment by Korijn** [comment]
Question: are you assuming our shadertoy implementation only supports GLSL? There are various examples with WGSL here. GLSL is _also_ supported, but it's not the primary shading language used in wgpu-py.

**Comment by Korijn** [comment]
@mikeny07 are you still interested in working on this?

ShaderToy is not a core feature of wgpu-py (the wgpu-native wrappers and the GUI backends are!) so it's not in a priority for us as maintainers.

If you're not interested to make the improvements and open a pull request, please close the issue. Thanks!

**Comment by mikeny07** [comment]
Thanks for the excellent work for porting WebGPU in Python. I am happy with the current ShaderToy that supports both WGSL and GLSL.
