### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#371]
### In short
In the update of #370, wgpu-native has become more permissive of errors. This means that with the new code, code/examples that have an error, will generate error messages, but they do not fail.

### Details
The wgpu-native lib notifies us of errors using a callback, i.e. errors are logged asynchronously. In the callback (`_on_error()`) we `logger.error()` the message, which displays it to the terminal. A second mechanism by which errors were communicated is that ids for new objects failed to set. We raised an error when this happened.

So previously, if the wgsl failed to compile, you'd first get an error being logged, and then an exception for the shader module not being created.

<details>
<summary>example shader error</summary>
<samp>
Running script: "/Users/almar/dev/py/wgpu-py/examples/triangle.py"

Shader error: label:  Some("")
Parsing error: unknown attribute: 'vertexx'

   ┌─ wgsl:10:1
   │
10 │ @vertexx
   │  ^^^^^^^ unknown attribute
   │
   = note:

Traceback (most recent call last):
  File "/Users/almar/dev/py/wgpu-py/examples/triangle.py", line 159, in <module>
    main(canvas)
  File "/Users/almar/dev/py/wgpu-py/examples/triangle.py", line 69, in main
    return _main(canvas, device)
  File "/Users/almar/dev/py/wgpu-py/examples/triangle.py", line 82, in _main
    shader = device.create_shader_module(code=shader_source)
  File "/Users/almar/dev/py/wgpu-py/wgpu/backends/rs.py", line 1287, in create_shader_module
    raise RuntimeError("Shader module creation failed")
RuntimeError: Shader module creation failed
</samp>
</details>

With the new version there is the logged error, but the module is still created, so later more errors get logged as the code tries to use an broken shader module. In effect, our examples-test considers the example to be ok.

### Possible solutions

1. In the example tests, detect whether errors have been logged. 
2. Detect whether errors have been logged in a few tactical places, e.g. when a command encoder is created.
3. Check for errors on every API call that makes calls into the lib, and raise them as Python exceptions.
4. Check for errors on every lib call.

I feel quite strongly that one of the last two options is the best way to go. If you try to create a shader-module with an incorrect shader, you simply want an exception asap. This means, however, that we'd need to include error-handling in nearly every method in `rs.py`. Maybe we can use a decorator or meta class to do that efficiently. 

@Korijn thoughts?

**Comment by Korijn** [comment]
We can provide a toggle to change the behaviour?

**Comment by almarklein** [comment]
> Perhaps it's possible to include information about the kind of error, the object or even the location in the shadercode in those exceptions.

The error messages (the ones now being printed, but which I propose would be raised as an exception) already contain nicely formatted information for shader errors. 👍 

> So having a verbosity setting that doesn't spam would be great to have.

The errors we talk a bout here are really errors, not warnings. So a verbosity level does not make much sense here, I think. One issue is where errors are repeatedly shown/raised on each draw, but we've measures for that already (in the function that invokes the draw).

> We can provide a toggle to control the behaviour?

That's possible, though I'd rather have a single behavior if that works for everyone.

I started this issue because I was not sure what to do, but as I wrote everything down, I feel quite strongly that raising the errors as exceptions is the most Pythonic way.

Also added a 4th option. I will have a stab with this and see how it works out.

**Comment by rajveermalviya** [comment]
To add to the possible solutions, there is also the [Error Scopes](https://gpuweb.github.io/gpuweb/#error-scopes) which can be used instead of the typical global uncaptured error callback. My bindings (Golang) uses this by wrapping each api call in a new scope and then a possible error is converted to the language error type.

For shader errors to be parseable though, there is still some incomplete work that needs to be done - [`wgpuShaderModuleGetCompilationInfo`](https://github.com/gfx-rs/wgpu-native/blob/46e345b35d0b362563859edeb21f124eb3f800b5/src/unimplemented.rs#L179-L186) is unimplemented which could provide:

```c
typedef struct WGPUCompilationInfo {
    WGPUChainedStruct const * nextInChain;
    size_t messageCount;
    WGPUCompilationMessage const * messages;
} WGPUCompilationInfo WGPU_STRUCTURE_ATTRIBUTE;

typedef struct WGPUCompilationMessage {
    WGPUChainedStruct const * nextInChain;
    WGPU_NULLABLE char const * message;
    WGPUCompilationMessageType type;
    uint64_t lineNum;
    uint64_t linePos;
    uint64_t offset;
    uint64_t length;
    uint64_t utf16LinePos;
    uint64_t utf16Offset;
    uint64_t utf16Length;
} WGPUCompilationMessage WGPU_STRUCTURE_ATTRIBUTE;
```

**Comment by almarklein** [comment]
> To add to the possible solutions, there is also the [Error Scopes](https://gpuweb.github.io/gpuweb/#error-scopes) which can be used instead of the typical global uncaptured error callback.

Thanks for the suggestion! Now I see how these can be useful. Though in the end routing the errors was just as easy to do for the uncaptured errors. I've now basically implemented an "error scope"  for each call into wgpu-native. So if something goes wrong, the Python exceptions points exactly to the call that generated the error.

> For shader errors to be parseable though, there is still some incomplete work that needs to be done

Already very happy that  the shader errors are now nicely formatted 👍
