### ISSUE TITLE
Idea to improve screenshot testing condition

### ISSUE THREAD

**Issue by Korijn** [pygfx/wgpu-py#375]
I have an idea to improve the check we use to toggle screenshot comparison in our test suite:

https://github.com/pygfx/wgpu-py/blob/f3a0bdff228e41121aeb03a4776a883b349addbe/examples/tests/test_examples.py#L95-L102

We can create a minimal pipeline that renders something that looks different between backends and platforms, and store a reference screenshot for the backend and OS that we use on CI.

Then at test time, instead of checking if we are on Linux and Lavapipe (just like we are on CI), we render that minimal example and see if we get an exact match with the reference.

If so, we can enable screenshot generation, and comparison.

This may make it possible to run screenshot generation and comparison on more combinations of OS and backend. :)

**Comment by almarklein** [comment]
Nice idea! Though I see two hurdles.

The viz rendered by that minimal pipeline would have to touch some stuff that is representative for things rendering different between platforms/backends.

What if that pipeline example fails because of an internal change in pygfx? I guess we should still detect lavapipe, i.e. do screenshot comparisons when `is_lavapipe or representative_example_matches`.

**Comment by kushalkolar** [comment]
I also like this idea!

**Comment by Korijn** [comment]
> Nice idea! Though I see two hurdles.
> 
> The viz rendered by that minimal pipeline would have to touch some stuff that is representative for things rendering different between platforms/backends.
> 
> What if that pipeline example fails because of an internal change in pygfx? I guess we should still detect lavapipe, i.e. do screenshot comparisons when `is_lavapipe or representative_example_matches`.

We can set an environment variable on CI to catch that it doesn't match while it is expected to.

**Comment by Korijn** [comment]
After thinking about this some more, it seems like it's an intractable problem. We'd have to create a stable visualization that knows exactly which pipeline features and data to exercise to cause hardware, platform & backend differences to show up. Otherwise it will be unpredictable and unreliable, since we need to be know with 100% certainty if the tests are expected to pass or not.
