### ISSUE TITLE
PySide 6.6 asyncio support 

### ISSUE THREAD

**Issue by Korijn** [pygfx/wgpu-py#383]
Great news from the PySide camp: https://www.qt.io/blog/qt-for-python-6.6

An official asyncio compatible Qt event loop!

See https://github.com/fork-tongue/observ/pull/93/files for an example of how to integrate.

The main benefit of supporting this in wgpu-py gui backends is that users will be able to use async/await syntax in the render function called by the canvas.

**Comment by almarklein** [comment]
Nice!!!
