### ISSUE TITLE
Renaming rs backend to native

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#393]
I called the wgpu-native backend `rs` because it was written in Rust, and perhaps the project was just called "wgpu" at that point?

Anyway, the `rs` is a bit weird now, so I propose to rename it. 

Implication wise, it means a lot of people will have to rewrite their import to `import wgpu.backends.native`, but this is easy to deprecate in a friendly way, and we've backwards incompatible changes that are more work to adjust t

**Comment by Korijn** [comment]
Can you think of a name that clearly signals who makes this backend? E.g. dawn is an easy name for dawn. :) But native is a little too ambiguous...

**Comment by toloudis** [comment]
`wgpu.backends.wgpu_native` might disambiguate it better from `wgpu.backends.dawn` because it uses the full name of the repo

**Comment by almarklein** [comment]
> But native is a little too ambiguous...

Yeah, I agree. I guess `wgpu_native` is the most clear option.

**Comment by Korijn** [comment]
> > But native is a little too ambiguous...
> 
> Yeah, I agree. I guess `wgpu_native` is the most clear option.

You could provide an alias `wn` if you want to make it easier to type. :)

**Comment by almarklein** [comment]
We could even consider `wgpu.backends.wgpu`, since wgpu-native is just a C-layer for the `wgpu` project 😕

**Comment by Korijn** [comment]
Although you're sort of joking, I do think `wgpu` is the right choice here as it seems to be the official project name.

**Comment by almarklein** [comment]
When working on the diagnostics, where we use the backend-name to refer to backend-specific diagnostics (e.g. `wgpu.diagnostics.rs_counts.print_report()`), I thought about this some more. I think the "wgpu" would be very confusing, and "wgpu_native" is awkwardly long, so I've come back to liking "native" the most, as the name that we use to refer to the wgpu-native backend. We can document what it refers to and add a link to the repo and all that.

**Comment by Korijn** [comment]
I think people less versed with the big picture will assume it means wgpu-py is using an OS native webgpu implementation.

**Comment by almarklein** [comment]
Myeah, I see what you mean, because the first line of wgpu code would be `import wgpu.backends.native`.

What if we do `import wgpu.backends.auto` (analog to gui.auto). Then the actual name we chose for the backend becomes less important, because users only see it in the diagnostics and a few other places. Plus we can switch the default backend in the future, or automatically use the JS backend if ppl use wgpu via pyscript :)
