### ISSUE TITLE
Use own created glfw window.

### ISSUE THREAD

**Issue by MackyK** [pygfx/wgpu-py#430]
I'm creating my own window with glfw. When I look at wgpu example its using wgpucanvas which creates the glfw window for you. How do I render with the window I created.

**Comment by almarklein** [comment]
Interesting! Could you tell us more about the use-case? Why can't you use the window that `GlfwWgpuCanvas`  creates for you? 

The wgpu canvas needs to hook up with the window to keep track of its size, when to redraw, etc. Knowing more about the why, can help us determine if/how this case can be supported.

**Comment by MackyK** [comment]
I'm using glfw to create the window then getting the HWND ptr to then changing the style of the window with pywin32. I need to have complete control of the styling of the window as most APIs that create the window for you don't allow this. Most windows created use the WS_CAPTION window style. I need to be able to create a window with the WS_THICKFRAME styling.

If wgpu exposed the GlfwWindow with WgpuCanvas. I could do the styling no problem.


```
canvas = WgpuCanvas()
window = wgpu.get_glfw_window(canvas)
hwnd = glfw.get_win32_window(window)

style = win32api.GetWindowLong(hwnd, win32con.GWL_STYLE)
style |= win32con.WS_THICKFRAME
style &= ~win32con.WS_CAPTION
win32api.SetWindowLong(hwnd, win32con.GWL_STYLE, style)
```

**Comment by almarklein** [comment]
I'm pretty sure that [canvas.get_window_id](https://wgpu-py.readthedocs.io/en/stable/generated/wgpu.gui.WgpuCanvasInterface.html#wgpu.gui.WgpuCanvasInterface.get_window_id) is the HWND that you're looking for. Incidentally wgpu needs it too to create a surface.

Otherwise you can try using `canvas._window` which is the glfw window reference. If you need this one, we can make it a public property to support use-cases like this.

Another option is to be able to pass a window object like `GlfwWgpuCanvas(... window=my_window)`. This may better if you'd need to initialize the window in a specific way.

**Comment by MackyK** [comment]
In all honesty I'd rather just have the bindings of wgpu made to work with python. I'd prefer to do most of the stuff myself to a degree. It's better for learning and It's easier to get help.

I hope this isn't coming across as rude. I'm grateful there is even a module for this on python. I hoping for something more barebones in the future.

**Comment by Korijn** [comment]
> In all honesty I'd rather just have the bindings of wgpu made to work with python. I'd prefer to do most of the stuff myself to a degree. It's better for learning and It's easier to get help.
> 
> I hope this isn't coming across as rude. I'm grateful there is even a module for this on python. I hoping for something more barebones in the future.

You can just read the source for our canvases and do it yourself with the bindings, just like we did. We're not forcing you to use the canvases in any way.

**Comment by almarklein** [comment]
To add to that, we have https://wgpu-py.readthedocs.io/en/stable/generated/wgpu.gui.WgpuCanvasInterface.html exactly for this reason (not forcing people into using our gui stuff). You can use it as an interface (duck-typing), but if you subclass it you only need to implement `get_window_id` and `get_physical_size`.

**Comment by almarklein** [comment]
I closed the issue, but if you have further questions feel free to ask!

**Comment by almarklein** [comment]
> Like I already said, you can decide not to use wgpu.gui and build everything yourself using the wrappers.

With the exception that wgpu needs a little information about the canvas, and a way to obtain a context. This is what the canvas interface is for.

**Comment by Korijn** [comment]
> With the exception that wgpu needs a little information about the canvas, and a way to obtain a context. This is what the canvas interface is for.

Well, yeah, but if you really want to build your own GUI layer, then that's exactly the part you need to do yourself right?

**Comment by almarklein** [comment]
Yes, the `WgpuCanvasInterface` is primarily a *specification*  of what you'd need to implement.
