### ISSUE TITLE
GPU info and identification

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#482]
## Purpose

In certain use-cases it's important for users to be able to select a specific GPU. In some cases a user may have installed multiple GPU's of the same kind. This issue is to to explore the possibilities.

## Related issues/prs

* #483
* #481
* https://github.com/gfx-rs/wgpu/discussions/5442
* #489
* https://github.com/pygfx/pygfx/pull/709

## Adapter info

The adapter info makes quite a journey ...

* As per the WebGPU spec, the adapter has a `request_adapter_info()` method that produces a dict. 
* The webgpu spec on the [GPUAdapterInfo interface](https://gpuweb.github.io/gpuweb/#gpuadapterinfo) lists just four fields (vendor, architecture, device, description), and these may even be empty when in the browser, for security reasons. In wgpu-py we produce the required fields, and more.
* In wgpu-core the [AdapterInfo struct]( https://github.com/gfx-rs/wgpu/blob/b34219ca214caea2af86dbb64a2a2b613ea5198c/wgpu-types/src/lib.rs#L1693-L1727) lists these fields: name, vendor (id), device (id), device_type, driver, driver_info, backend.
* In webgpu.h the [AdapterProperties struct](https://github.com/webgpu-native/webgpu-headers/blob/d02fec1b96af29695b9f5659a91067a241f40b04/webgpu.h#L753-L763) specifies these fields: vendorID, vendorName, architecture, deviceID, name, driverDescription, adapterType, backendType
* In wgpu-native the Rust struct is [mapped](https://github.com/gfx-rs/wgpu-native/blob/1ac3a5c561b2ed89abb199f3c538179b62363d5f/src/lib.rs#L701-L737) to the C struct.
* And in wgpu-py we [map](https://github.com/pygfx/wgpu-py/blob/570738c9b9dcf49e734cf7cea7cb0cf925a785f9/wgpu/backends/wgpu_native/_api.py#L283-L296) the C struct to the WebGPU dict.

This sketch shows how the fields are mapped at each step (if you can decipher my handwriting):

![7226AD99-4155-45FE-A8CB-4B76A6ADE7AA_4_5005_c](https://github.com/pygfx/wgpu-py/assets/3015475/1aa59c1d-f8f8-4bcf-8055-f4620a6a44d4)

## Addressing a GPU when multiple are present

In a typical multi-gpu setup, you likely want to address the GPU's by index, because the GPU's look the same in terms of their properties. However, this means the order must be consistent and match e.g. pytorch.

Or ... there should be some sort of UUID to identify a device. On Vulkan there is `pipelineCacheUUID` from [VkPhysicalDeviceProperties](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceProperties.html). On Metal there is the device's [registryId](https://developer.apple.com/documentation/metal/mtldevice/2915737-registryid) property. TODO: is any of this exposed by Torch? Looks like [its not](https://github.com/pytorch/pytorch/blob/72662bf05b3499ce96aae9183a489c78f0c44c84/torch/_C/__init__.pyi.in#L1779-L1788)?

Some refs:
* https://stackoverflow.com/questions/52815708/order-of-cuda-devices
* https://github.com/gfx-rs/wgpu/discussions/5442
* https://github.com/KhronosGroup/Vulkan-Loader/issues/153

## Testing

To get a nice list of devices on your machine:
```py
import json
import wgpu

for adapter in wgpu.gpu.enumerate_adapters():
    print(json.dumps(adapter.request_adapter_info(), indent=4))
```

Feel free to post the result in a comment below. Would be nice to have some real life examples.

## Observations

*editing as more comes in*

* Vendor and description are empty in quite a few cases.
* Device name seems always present.
* But multiple adaptes with the same device name can be present, with different backend_type.
* The vendor_id and device_id together seem to be pretty unique to identify a device (check as more comes in), but can be the same with differen backends.
* Multiple GPU's of the same type look exactly the same 🤔

**Comment by almarklein** [comment]
Here's my Linux machine:
```
{
    "vendor": "Intel open-source Mesa driver",
    "architecture": "",
    "device": "Intel(R) UHD Graphics 730 (ADL-S GT1)",
    "description": "Mesa 23.2.1-1ubuntu3.1~22.04.2",
    "adapter_type": "IntegratedGPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "llvmpipe",
    "architecture": "",
    "device": "llvmpipe (LLVM 15.0.7, 256 bits)",
    "description": "Mesa 23.2.1-1ubuntu3.1~22.04.2 (LLVM 15.0.7)",
    "adapter_type": "CPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Mesa Intel(R) UHD Graphics 730 (ADL-S GT1)",
    "description": "",
    "adapter_type": "IntegratedGPU",
    "backend_type": "OpenGL"
}
```

**Comment by almarklein** [comment]
Options are quite limited on my Mac:
```
{
    "vendor": "",
    "architecture": "",
    "device": "Apple M1 Pro",
    "description": "",
    "vendor_id": 0,
    "device_id": 0,
    "adapter_type": "IntegratedGPU",
    "backend_type": "Metal"
}
```

**Comment by almarklein** [comment]
On Windows (no external GPU):
```
{
    "vendor": "Intel Corporation",
    "architecture": "",
    "device": "Intel(R) UHD Graphics 730",
    "description": "Intel driver",
    "vendor_id": 32902,
    "device_id": 18066,
    "adapter_type": "IntegratedGPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Intel(R) UHD Graphics 730",
    "description": "",
    "vendor_id": 32902,
    "device_id": 18066,
    "adapter_type": "IntegratedGPU",
    "backend_type": "D3D12"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Microsoft Basic Render Driver",
    "description": "",
    "vendor_id": 5140,
    "device_id": 140,
    "adapter_type": "CPU",
    "backend_type": "D3D12"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Intel(R) UHD Graphics 730",
    "description": "",
    "vendor_id": 32902,
    "device_id": 0,
    "adapter_type": "IntegratedGPU",
    "backend_type": "OpenGL"
}
```

**Comment by Vipitis** [comment]
I am getting the following on my Windows machine (single GPU):

```json
{
    "vendor": "Intel Corporation",
    "architecture": "",
    "device": "Intel(R) Arc(TM) A750 Graphics",
    "description": "Intel driver",
    "vendor_id": 32902,
    "device_id": 22177,
    "adapter_type": "DiscreteGPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Intel(R) Arc(TM) A750 Graphics",
    "description": "",
    "vendor_id": 32902,
    "device_id": 22177,
    "adapter_type": "DiscreteGPU",
    "backend_type": "D3D12"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Microsoft Basic Render Driver",
    "description": "",
    "vendor_id": 5140,
    "device_id": 140,
    "adapter_type": "CPU",
    "backend_type": "D3D12"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Intel(R) Arc(TM) A750 Graphics",
    "description": "",
    "vendor_id": 32902,
    "device_id": 0,
    "adapter_type": "IntegratedGPU",
    "backend_type": "OpenGL"
}
```

**Comment by kushalkolar** [comment]
On my linux (Debian 11) desktop with 2 discrete GPUs:

```json
{
    "vendor": "radv",
    "architecture": "",
    "device": "AMD RADV POLARIS10 (ACO)",
    "description": "Mesa 20.3.5 (ACO)",
    "vendor_id": 4098,
    "device_id": 26591,
    "adapter_type": "DiscreteGPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "llvmpipe",
    "architecture": "",
    "device": "llvmpipe (LLVM 11.0.1, 256 bits)",
    "description": "Mesa 20.3.5 (LLVM 11.0.1)",
    "vendor_id": 65541,
    "device_id": 0,
    "adapter_type": "CPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "NVIDIA",
    "architecture": "",
    "device": "NVIDIA GeForce RTX 3080",
    "description": "530.30.02",
    "vendor_id": 4318,
    "device_id": 8710,
    "adapter_type": "DiscreteGPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Radeon RX 570 Series (POLARIS10, DRM 3.40.0, 5.10.0-21-amd64, LLVM 11.0.1)",
    "description": "",
    "vendor_id": 4098,
    "device_id": 0,
    "adapter_type": "Unknown",
    "backend_type": "OpenGL"
}
```

**Comment by almarklein** [comment]
Wow, why is llvmpipe listed above your nvidia gpu 😮

**Comment by Vipitis** [comment]
here is a Windows laptop with iGPU and dGPU

```json
{
    "vendor": "Intel Corporation",
    "architecture": "",
    "device": "Intel(R) Iris(R) Xe Graphics",
    "description": "Intel driver",
    "vendor_id": 32902,
    "device_id": 39497,
    "adapter_type": "IntegratedGPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "NVIDIA",
    "architecture": "",
    "device": "NVIDIA T500",
    "description": "537.79",
    "vendor_id": 4318,
    "device_id": 8123,
    "adapter_type": "DiscreteGPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "",
    "architecture": "",
    "device": "NVIDIA T500",
    "description": "",
    "vendor_id": 4318,
    "device_id": 8123,
    "adapter_type": "DiscreteGPU",
    "backend_type": "D3D12"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Intel(R) Iris(R) Xe Graphics",
    "description": "",
    "vendor_id": 32902,
    "device_id": 39497,
    "adapter_type": "IntegratedGPU",
    "backend_type": "D3D12"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Microsoft Basic Render Driver",
    "description": "",
    "vendor_id": 5140,
    "device_id": 140,
    "adapter_type": "CPU",
    "backend_type": "D3D12"
}
{
    "vendor": "",
    "architecture": "",
    "device": "Intel(R) Iris(R) Xe Graphics",
    "description": "",
    "vendor_id": 32902,
    "device_id": 0,
    "adapter_type": "IntegratedGPU",
    "backend_type": "OpenGL"
}
```

**Comment by Vipitis** [comment]
I tried it on a IDC instance, since there is multiple GPUs... well the Intel data center kind and they don't really work for display out either and I don't have all the permissions it seems.

```json
error: XDG_RUNTIME_DIR not set in the environment.
No windowing system present. Using surfaceless platform
MESA: warning: Driver does not support the 0xbda PCI ID.
libEGL warning: egl: failed to create dri2 screen
MESA: warning: Driver does not support the 0xbda PCI ID.
libEGL warning: egl: failed to create dri2 screen
libEGL warning: failed to open /dev/dri/card4: Permission denied

libEGL warning: failed to open /dev/dri/card3: Permission denied

libEGL warning: failed to open /dev/dri/card2: Permission denied

libEGL warning: failed to open /dev/dri/card0: Permission denied

No config found!
No config found!
MESA: warning: Driver does not support the 0xbda PCI ID.
MESA: warning: Driver does not support the 0xbda PCI ID.
MESA: warning: Driver does not support the 0xbda PCI ID.
MESA: warning: Driver does not support the 0xbda PCI ID.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
{
    "vendor": "llvmpipe",
    "architecture": "",
    "device": "llvmpipe (LLVM 15.0.7, 256 bits)",
    "description": "Mesa 24.0.0-devel (git-3ca1f35cbf) (LLVM 15.0.7)",
    "vendor_id": 65541,
    "device_id": 0,
    "adapter_type": "CPU",
    "backend_type": "Vulkan"
}
{
    "vendor": "",
    "architecture": "",
    "device": "llvmpipe (LLVM 15.0.7, 256 bits)",
    "description": "",
    "vendor_id": 65541,
    "device_id": 0,
    "adapter_type": "CPU",
    "backend_type": "OpenGL"
}
```

**Comment by almarklein** [comment]
> here is a Windows laptop with iGPU and dGPU

At least we see consistently that all Vulkan apdaters are on top, as [said](https://github.com/gfx-rs/wgpu/discussions/5442) by the wgpu-core folks. Interestingly, Vulkan and D3D12 report the two devices in opposite order 🤔

**Comment by kushalkolar** [comment]
I guess if there is no nice way to identify GPUs across wgpu and torch, jax, etc. we can document this and provide users with ideas for how they can ID the GPUs for their use cases, such as looking at VRAM usage.

**Comment by almarklein** [comment]
Well, we can ask whether wgpu-core is open to adding an opaque uid field to the adapter properties, that is then filled in by Vulkan/Metal/D3D12 (e.g. Vulkan has `pipelineCacheUUID`). The question is then whether Jax and Torch allow querying the same uid.

**Comment by almarklein** [comment]
I had some hope looking into Vulkan's `pipelineCacheUUID` which according to the [docs](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceProperties.html) represents a universally unique identifier for the device. Not so unique though:
```
In [10]: import vulkan as vk
    ...:
    ...: appInfo = vk.VkApplicationInfo(
    ...:     sType=vk.VK_STRUCTURE_TYPE_APPLICATION_INFO,
    ...:     pApplicationName="Test",
    ...:     applicationVersion=vk.VK_MAKE_VERSION(1, 0, 0),
    ...:     pEngineName="No Engine",
    ...:     engineVersion=vk.VK_MAKE_VERSION(1, 0, 0),
    ...:     apiVersion=vk.VK_API_VERSION_1_0)
    ...:
    ...: layers = []
    ...: extensions = []
    ...:
    ...: createInfo = vk.VkInstanceCreateInfo(
    ...:     sType=vk.VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
    ...:     flags=0,
    ...:     pApplicationInfo=appInfo,
    ...:     enabledExtensionCount=len(extensions),
    ...:     ppEnabledExtensionNames=extensions,
    ...:     enabledLayerCount=len(layers),
    ...:     ppEnabledLayerNames=layers)
    ...:
    ...: instance = vk.vkCreateInstance(createInfo, None)
    ...:
    ...: for device in vk.vkEnumeratePhysicalDevices(instance):
    ...:     info = vk.vkGetPhysicalDeviceProperties(device)
    ...:     print(info.deviceName, bytes(info.pipelineCacheUUID).hex())
    ...:
Tesla V100-SXM2-32GB 4855a349fbccc79ebb585ae9e8dd488e
Tesla V100-SXM2-32GB 4855a349fbccc79ebb585ae9e8dd488e
Tesla V100-SXM2-32GB 4855a349fbccc79ebb585ae9e8dd488e
llvmpipe (LLVM 16.0.6, 256 bits) 742d3363613166333563626629616161
```

**Comment by almarklein** [comment]
Another experiment using the following:
```py
import wgpu, torch, subprocess

def use_data_in_wgpu(idx):
    a = wgpu.gpu.enumerate_adapters()[idx]
    d = a.request_device()
    b = d.create_buffer(size=10*2**20, usage=wgpu.BufferUsage.COPY_DST)
    return b

def  use_data_in_torch(idx):
    return torch.ones([2000, 10], dtype=torch.float64, device=torch.device(f"cuda:{idx}"))

def show_mem_usage():
    print(subprocess.run(["nvidia-smi"]))
```

... shows that Vulkan's order is the same as the order of Cuda/nvidia. At least on the env I was on. I tried with 3 and 4 gpu's. This was on a cluster without any of the gpu's connected to a display. I don't know if this holds up e.g. in a physical machine if multiple of the same gpu's are present, and one is connected to a display. Or if multiple devices of the same type are present.

> we can document this and provide users with ideas for how they can ID the GPUs for their use cases, such as looking at VRAM usage.

I come to the same conclusion. Maybe we can tell that on a gpu-cluster the order likely matches pytorch, but we make no guarantees.

**Comment by almarklein** [comment]
@Vipitis On that Windows machine with inconsistent order, do you have PyTorch installed and can you try:
```py
import torch
for i in range(torch.cuda.device_count()):
   print(torch.cuda.get_device_properties(i).name)
```

**Comment by kushalkolar** [comment]
> Not so unique though:
>```
> Tesla V100-SXM2-32GB 4855a349fbccc79ebb585ae9e8dd488e
> Tesla V100-SXM2-32GB 4855a349fbccc79ebb585ae9e8dd488e
> Tesla V100-SXM2-32GB 4855a349fbccc79ebb585ae9e8dd488e
> ```

:upside_down_face: 

> Maybe we can tell that on a gpu-cluster the order likely matches pytorch, but we make no guarantees.

Yea I think these large buffer creation functions are a good starting point for anyone to manually ID their GPUs. Perhaps having a function like `pygfx.set_default_gpu(<adapter>)` and allowing `adapter` as a kwarg to `pygfx.WgpuRenderer` is the best solution.

**Comment by almarklein** [comment]
> having a function like `pygfx.set_default_gpu(<adapter>)`

Ah, and then someone could write:
```py
gfx.set_default_gpu(wgpu.gpu.enumerate_adapters()[0])
# or
adapter = [a for a in wgpu.gpu.enumerate_adapters() if "GeForce" in a.summary][0]
gfx.set_default_gpu(adapter)

# or 
discrete_adapters = [a for a in wgpu.gpu.enumerate_adapters() if "DiscreteGPU" in a.summary]
gfx.set_default_gpu(discrete_adapters[5])
```

After some thought I think I like this better than having the selection logic in pygfx. It does move some of the complexity onto the user, but its (nearly) a one-liner, and makes it more explicit how the selection actually takes place.

Let's call it `gfx.set_adapter()` though. 

Supporting per-renderer adapters is not in scope for the time being. (There's #492 and supporting it would need another level of indirection in storing pipeline objects in `pipeline.py`)

**Comment by Vipitis** [comment]
> @Vipitis On that Windows machine with inconsistent order, do you have PyTorch installed and can you try:
> 
> ```python
> import torch
> for i in range(torch.cuda.device_count()):
>    print(torch.cuda.get_device_properties(i).name)
> ```

well, on the laptop there is only a single cuda GPU, so I am only getting that of course. The iGPU wouldn't even be an XPU with IPEX as far as I know.

Not sure if the default behaviour should be dGPU instead of iGPU for wgpu. As for heavier tasks the dGPU should be better and also

**Comment by almarklein** [comment]
Concluding this issue: its seems impossible to uniquely identify a GPU, and we cannot reliably rely on their reported order (although the order seems consistent with Cuda on a gpu cluster). Therefore we will provide users with tools to make a selection, but not implement any kind of selection mechanics in wgpu/pygfx/fastplotlib.

Closed by https://github.com/pygfx/pygfx/pull/709
