### ISSUE TITLE
Retry release for v0.15.1 ?

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/wgpu-py#488]
Seems like upload to pypi failed yesterday: https://github.com/pygfx/wgpu-py/actions/runs/8466766582/job/23196326522#step:9:60 

Others seem to have had similar issues with the action yesterday: https://github.com/pypa/gh-action-pypi-publish/issues/224

**Comment by almarklein** [comment]
Thanks for the heads-up!

I restarted the failed release built yesterday, but then it failed because it tried to create a GH release that already existed. So just now, I deleted that, and ran the failed step *again* ... and now it looks we're all good. Pypi has the new release.
