### ISSUE TITLE
create_buffer_with_data requires data to be a multiple of COPY_BUFFER_ALIGNMENT

### ISSUE THREAD

**Issue by fyellin** [pygfx/wgpu-py#512]
The helper function `create_buffer_with_data` gives an error if the data it passes is not a multiple of 4.

Here is a reasonable use case for why I would want to do that:

I have an external model that includes vertices, normals, and indices of triangles.  These models are often written by others
```
     vertices_array = np.array(model.vertices, dtype=np.float32)
     vertices_buffer = device.create_buffer_with_data(vertices_array, usage=BufferUsage.VERTEX)
      . . .
     indices_array = np.array(model.indices, dtype=uint16)
     indices_buffer = device.create_buffer_with_data(indices_array, usage=BufferUsage.INDEX)
      . . . 
     encoder.set_index_buffer(indices_buffer, "uint16")
     encoder.draw_index(len(indices_array))
```
This works fine, unless the model happens to have an odd number of indexes. In that case, the byte size of `indices_array` will not be a multiple of 4, and the code fails.

There are solutions around the problem, but they are not always pretty:

1.  I can test the length of `model.indices` and add a junk element to the end if it is odd.  But note that this information belongs to someone else, and may be readonly.
2. I can just avoid using `create_buffer_with_data`, but perform the mapping myself.

But since `create_buffer_with_data` is a convenience function and not subject to a WebGPU specification, I think it's reasonable for it to always round up the size to a multiple of 4.  This could either (1) always be done, since it is invisible to the user or (2) be done if the user specifies `allows_padding` or something like that, indicating that they are aware of the problem.

**Comment by panxinmiao** [comment]
I believe this should not be handled by wgpu-py. It is the responsibility of the user program to manage the byte data written to the buffer, including byte alignment, padding, and other considerations. Since this is a very low-level API, it should not make any assumptions about the content written to the buffer nor be responsible for it. 
For example, vertex attributes need to be aligned to 4 bytes, while storage buffers and uniform buffers require 16-byte alignment (and their structure members also needing alignment according to the WebGPU specification). 

Let's see what Almar thinks. :)

**Comment by fyellin** [comment]
May I suggest a different fix that's more in the spirit of the API? Add a bytes argument. If omitted, it defaults to the size of the memory view. It must always be larger. 

This would let me use create_buffer_with_data in cases where I have gotten the info from elsewhere and can't grow it.

**Comment by fyellin** [comment]
I realize that this is a different implementation, but on my browser I tried:

```
> x = device.createBuffer({size: 6, usage: GPUBufferUsage.VERTEX, mappedAtCreation: true})
```
and it returned me a buffer, without complaint.

**Comment by panxinmiao** [comment]
> I realize that this is a different implementation, but on my browser I tried:
> 
> ```
> > x = device.createBuffer({size: 6, usage: GPUBufferUsage.VERTEX, mappedAtCreation: true})
> ```
> 
> and it returned me a buffer, without complaint.

Interesting, but the WebGPU specification explicitly states that this is incorrect.

See: https://www.w3.org/TR/webgpu/#dom-gpudevice-createbuffer

![image](https://github.com/pygfx/wgpu-py/assets/8044566/2a9aaec5-e1d4-480c-b77e-3f35a2456db9)

Moreover, when calling `writeBuffer()`, it is also required that the number of bytes written must be a multiple of 4.

**Comment by panxinmiao** [comment]
I did a quick test on Chrome browser.
![image](https://github.com/pygfx/wgpu-py/assets/8044566/879899bc-199c-403f-9182-060d7c118c2f)

While the buffer object can be created, continuing to call the `getMappedRange()` method throws an error. 
I suspect that before calling `getMappedRange()`, it is only a JavaScript object and has not actually created a GPU object. 
However, regardless, I feel that Chrome's implementation of this API may not fully comply with the specification. 😅

**Comment by almarklein** [comment]
I agree with @panxinmiao that alignment is ultimately the caller's responsibility. But I can also see that in a method like `create_buffer_with_data()` we can provide some convenience to make it easier for the user to manage alignment. My proposal would be a `align_bytes` arg that can be set to e.g. 4 or 16. Does that make sense @fyellin ?

**Comment by fyellin** [comment]
Sure.  That sounds reasonable.  My original proposal, I suppose, was just to make `align_bytes=4` be the default.  But I like the idea of making the user be responsible for it.

I can implement this, if you want.

**Comment by almarklein** [comment]
> I can implement this, if you want.

That would be great! 🙏 

> to make `align_bytes=4` be the default.

Mmm, it's tempting, but I think better that the user must explicitly set it to use alignment. That way it's explicit that something related to alignment is happening. And easier for the user to spot why this works, and manual mapping does not.

**Comment by fyellin** [comment]
@panxinmiao.  You are correct.  The only use case I have is an index buffer.  Programs that generate wire-frame models don't necessarily know that they are producing them for a GPU, and may not pad them appropriately.  This is the one case where the user is using external data rather than arrays that they are creating themselves.

**Comment by almarklein** [comment]
Good point @panxinmiao !

**Comment by fyellin** [comment]
I think I'm going to re-open this.  Over the weekend I looked at the C WGPU API and they handle this situation.  The documentation is that it gets rounded up to a multiple of 4.  Turns out to be easy to do.
