### ISSUE TITLE
Imgui overlay render with offscreen canvas

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/wgpu-py#542]
Currently the offscreen canvases, such as the jupyter offscreen canvas and the manual offscreen canvas, do not display imgui renders as overlays with alpha blending after a previous render pass has been performed with for example pygfx. This works on the glfw and qt canvas.

For example, on glfw:

![image](https://github.com/user-attachments/assets/d7a24bbe-900f-4114-a3a3-0d770401f5dd)

With jupyter_rfb and manual offscreen canvas:
- if `imgui_renderer.render()` is called last, then only imgui is displayed
- if the pygfx `renderer.render(scene, camera)` is called last, then that's the only thing that's displayed

![image](https://github.com/user-attachments/assets/1001a747-1c01-4aeb-a68e-77f363b933f3)

 I've been looking into the [`GPUCanvasContext`](https://github.com/pygfx/wgpu-py/blob/e57b3e14ccea108fa863205e61d82d8d203e37cd/wgpu/gui/offscreen.py#L7-L82) specific to offscreen canvanses, and the `WgpuOffscreenCanvasBase` and can't quite seem to find exactly what's causing this difference. 

```python
import numpy as np

from imgui_bundle import imgui
from wgpu.gui.auto import WgpuCanvas, run
from wgpu.utils.imgui import ImguiRenderer


import pygfx

canvas = WgpuCanvas()
renderer = pygfx.WgpuRenderer(target=canvas, blend_mode="weighted_plus")

imgui_renderer = ImguiRenderer(renderer.device, canvas)

# random scatter of 100 points
data = np.random.normal(size=(100, 3)).astype(np.float32)

points = pygfx.Points(
    geometry=pygfx.Geometry(positions=data),
    material=pygfx.PointsMaterial(size=20, color=(1., 1., 1., 0.5))
)

scene = pygfx.Scene()
camera = pygfx.OrthographicCamera()

scene.add(points)
camera.show_object(scene)


def update_gui():
    imgui.new_frame()

    imgui.set_next_window_pos((0, 10), imgui.Cond_.appearing)
    imgui.set_next_window_size((300, 0), imgui.Cond_.appearing)

    imgui.begin("window", None)

    changed, new_size = imgui.slider_float(label="pointer_size", v=points.material.size, v_min=1.0, v_max=50.0)
    if changed:
        points.material.size = new_size

    imgui.end()
    imgui.end_frame()
    imgui.render()

    return imgui.get_draw_data()


imgui_renderer.set_gui(update_gui)


def animate():
    renderer.render(scene, camera)

    imgui_renderer.render()

    canvas.request_draw()


canvas.request_draw(animate)
run()
```

**Comment by panxinmiao** [comment]
Ah, We need to access the same texture in different rendering subsystems.

See: https://github.com/pygfx/wgpu-py/pull/516#discussion_r1647141675

**Comment by kushalkolar** [comment]
> Ah, We need to access the same texture in different rendering subsystems.
> 
> See: [#516 (comment)](https://github.com/pygfx/wgpu-py/pull/516#discussion_r1647141675)

I figured it was something like that but couldn't figure out where exactly it's kept, thanks! :smile:
