### ISSUE TITLE
Test suite appears to be broken on github

### ISSUE THREAD

**Issue by fyellin** [pygfx/wgpu-py#548]
Test suite is failing on git hub. Even "main", which used to pass, is failing.

Multiple tests are failing with:

```
      ImportError: cannot import name 'get_platform' from 'wheel.bdist_wheel' (/tmp/pip-build-env-o1du4o99/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py)
      [end of output]
```
The github runner image was updated on 30 July.

**Comment by Korijn** [comment]
It's likely caused by a new version of the wheel package or one of it's dependencies (e.g. setuptools).

**Comment by fyellin** [comment]
The release comments for wheel sure makes it seem like the guilty party.

```
0.44.0 (2024-08-04)
Canonicalized requirements in METADATA file (PR by Wim Jeantine-Glenn)
Deprecated the bdist_wheel module, as the code was migrated to setuptools itself
```

**Comment by fyellin** [comment]
wheel.bdist_wheel no longer contains get_platform.  Have to get that from elsewhere.

**Comment by Vipitis** [comment]
is there a known combination for wheel and setup tools dependencies that works? I was running into this yesterday when trying to install from the repo

**Comment by fyellin** [comment]
I'm travelling for the next few days, so I'm cancelling my pull request and going to let someone else take care of this.  The bug is in setup.py.  That version of `get_platform` doesn't exist anymore.  It needs to be pulled from sysconfig or elsewhere.

**Comment by fyellin** [comment]
My goal here was to do the minimal possible to get the build working again. 

I'm happy to make the other changes, too, if you want me to. But they don't feel urgent.

**Comment by fyellin** [comment]
Seems to be fixed with recent pull request
