### ISSUE TITLE
branch "main" is failing on Mac running Python 12.

### ISSUE THREAD

**Issue by fyellin** [pygfx/wgpu-py#600]
The current `main` branch is failing one of these tests when I run it on my Mac.  This only started failing today.
In GPU.requestAdapter, there is the code

```
        if canvas is not None:
            surface_id = canvas._surface_id  # can still be NULL
```

The test `test_glfw_canvas_render_custom_canvas` is failing because the `canvas` object in that test doesn't have a `_surface_id`. Presumably when this test is run on other OSs, `canvas` is not None??

**Comment by fyellin** [comment]
Ah.  The problem is that the Linux test suite isn't running these tests at all.  It never installs glfw, so these tests aren't run.

These tests need to be run, (so fix the test suite runner), and the tests need to be fixed.

**Comment by almarklein** [comment]
I also saw this bug when I ran the tests locally. I plan to fix it this week.

> These tests need to be run, (so fix the test suite runner), and the tests need to be fixed.

I can give it a try, but IIRC, this test cannot work on CI because there's no screen for gflw to create a window for.
