### ISSUE TITLE
Example of creating a point cloud visualisation?

### ISSUE THREAD

**Issue by asmith26** [pygfx/wgpu-py#619]
Hi there,

I was wondering if I can use this lib to visualize (ideally interactively) a  >1million points 3D-point cloud. Not sure if there are any examples for this?

Many thanks for any help, and this lib! :)

**Comment by almarklein** [comment]
You sure could, but if you're looking for an easy solution, I'd recommend taking a look at [pygfx](pygfx), here's the gallery, which includes several examples that use some form of a point cloud.
