### ISSUE TITLE
Where does webgpu.idl come from?

### ISSUE THREAD

**Issue by fyellin** [pygfx/wgpu-py#646]
`webgpu.idl` clearly states that it is a generated file, but I cannot find any instructions on how or where it is generated.

I cannot find any information on where it comes from either here on in gfx-rs.  I'm curious to see how easy or difficult to update wgpu-py to the newest wgpu-native library, but that's impossible to do without also updating the idl.

**Comment by fyellin** [comment]
Hmm.  I just found something in codegen/README.md that I didn't realize was a link.  Is that where we're supposed to download?

**Comment by Korijn** [comment]
I believe it's this: https://www.w3.org/TR/webgpu/#idl-index

**Comment by Korijn** [comment]
> Hmm. I just found something in codegen/README.md that I didn't realize was a link. Is that where we're supposed to download?

That's right

**Comment by almarklein** [comment]
This one: https://gpuweb.github.io/gpuweb/webgpu.idl I think this is the repo that generates the file: https://github.com/gpuweb/gpuweb
