### ISSUE TITLE
Query version of wgpu-native?

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#82]
We know the version of our own lib, but if someone uses their own lib, it would be nice to be validate that the versions match.

**Comment by Korijn** [comment]
Interesting. I'd say we can learn how to do this by checking out auditwheel's source

**Comment by almarklein** [comment]
As a starter, we can report the version of wgpu-native that we expect (and have shipped).

**Comment by almarklein** [comment]
https://github.com/gfx-rs/wgpu-native/pull/13

**Comment by almarklein** [comment]
Done in #96
